version: "3"

networks:
  course-platform:
    external: true

services:
  main-server:
    container_name: main-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:80"
    networks: 
      - course-platform