version: "3"

services:
  main-server:
    container_name: main-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "80:80"